apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::314325668782:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-26FF73R5FN93
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::314325668782:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T20:21:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1388"
  uid: 13afee26-0481-4100-9428-f6569e8a12c7
